### ISSUE TITLE
Python Resources Spam Link

### ISSUE THREAD

**Issue by apples723** [bregman-arie/devops-resources#8]
## Summary 
I've found that the link in resources under [python](https://github.com/bregman-arie/devops-resources/blob/master/resources/python.md#resources) to be invalid and the linked address takes you to an ad redirect. 
### Details
*Resource Name*: [pippython.com](pippython.com)
*Redirect Site*: [0redirb.com](0redirb.com)

Suggest removing the link from the list.

**Comment by bregman-arie** [comment]
Fixed. Thank you.
